### PR TITLE
Fix infinite loop in _tryWalkUp

### LINKED ISSUE #6465: Something in hover provider broke in a commit released in 1.1.333
Hover suggestion just shows "loading" when I hit Ctrl+Space in a custom Monaco setup.

Expected behavior: Should show something, whether a keyword, or a name, or something similar.

Bug Screenshot
image

The bug seems to occur on 1.1.333 and after.

So, I decided to set up a development instance of pyright, and integrate it into my custom Monaco setup. After some digging I've concluded that the offending commit is `* cfe56bfb3 pull-pylance-with-pyright-1.1.332 (#6195)`

I've been trying to track down the offending changes in the above commit, but I've been coming up short.
edit: I think the offending changes are in `packages/pyright-internal/src/common/pathUtils.ts`

Any additional information I can get for you, let me know. Thanks!

### PR DESCRIPTION
**Pull request by rchiodo**
Non file URIs don't ever indicate diskPathRoot, so double check we're not going to loop forever.
Fixes #6465 

Should also fix https://github.com/microsoft/pyright/issues/6314

### CODE REVIEW

File: packages/pyright-internal/src/analyzer/importResolver.ts [hunk 1]
```diff
@@ -199,7 +199,7 @@ export class ImportResolver {
             );
 
             let success;
-            [success, current] = this._tryWalkUp(current);
+            [success, current] = this._(current);
```
Comment (debonte) [inline packages/pyright-internal/src/analyzer/importResolver.ts:202]: How does this work? What is `this._`?

Comment (rchiodo) [reply packages/pyright-internal/src/analyzer/importResolver.ts:202]: What the hell? Where did that happen?

Comment (rchiodo) [reply packages/pyright-internal/src/analyzer/importResolver.ts:202]: Uggh, that's what I get for using the github browser editor.

**Review by debonte — APPROVED** [review]

File: packages/pyright-internal/src/tests/samples/stubs/placeholder.txt
[the remark this answers is not in the document]
Comment (rchiodo) [reply packages/pyright-internal/src/tests/samples/stubs/placeholder.txt:1]: It's so the directory is created. You can't add an empty directory in git AFAICT. 

I'll add a bit of text explaining that.

**Review by erictraut — APPROVED** [review]
