### PR TITLE
Fix 1.1.405 regressions

### LINKED ISSUE #11321: Regression in 1.1.405 involving loops
**Describe the bug**
A clear and concise description of the behavior you are seeing and the expected behavior along with steps to reproduce it.
Pyright seems to be confused about variable type when modifying said variable inside the loop.
In this example, `lines` should infer as `list[str]`.

**Code or Screenshots**

```python
lines = ["ab", "bc", "ac", "ca"]  # lines: list[str]
while lines:  # lines: list[str] | list[str | Unknown]
    print(lines)  # lines: list[str] | list[Unknown]
    lines = [x for x in lines[1:]]  # x: str | Unknown
```
Working fine in [1.1.404](https://pyright-play.net/?pyrightVersion=1.1.404&strict=true&code=DYSwdgpgzgBAvDA2gIgIYCNkBobPQY211UJ2X1WQF0AoAdwAsRgIZRIoAuGmXmABwBO4AC4AKdtACUPPpNgJEADxgAzAPaCYK8G3DREARk5VaQA)
Broken in [1.1.405](https://pyright-play.net/?pyrightVersion=1.1.405&strict=true&code=DYSwdgpgzgBAvDA2gIgIYCNkBobPQY211UJ2X1WQF0AoAdwAsRgIZRIoAuGmXmABwBO4AC4AKdtACUPPpNgJEADxgAzAPaCYK8G3DREARk5VaQA)
Still broken in [1.1.408](https://pyright-play.net/?pyrightVersion=1.1.408&strict=true&code=DYSwdgpgzgBAvDA2gIgIYCNkBobPQY211UJ2X1WQF0AoAdwAsRgIZRIoAuGmXmABwBO4AC4AKdtACUPPpNgJEADxgAzAPaCYK8G3DREARk5VaQA) (latest version as of today)

### PR DESCRIPTION
**Pull request by gramster**
Fix 1.1.405 regressions: use position check instead of isFlowPathBetweenNodes in inferTypeOfSymbolForUsage

Fix: replace the isFlowPathBetweenNodes call with a simple source-position check. Skip declarations that textually appear after the usage (these can only be reached via loop back-edges). Retain declarations that appear before the usage (preserving the #10850 fix for type aliases like JSON = ... used in JSONObjectOf[JSON]).

Should fix https://github.com/microsoft/pyright/issues/11321, https://github.com/microsoft/pyright/issues/11076 and https://github.com/microsoft/pyright/issues/11359

### CODE REVIEW

File: packages/pyright-internal/src/analyzer/typeEvaluator.ts [hunk 1]
```diff
@@ -23304,7 +23304,15 @@ export function createTypeEvaluator(
                     const usageScope = ParseTreeUtils.getExecutionScopeNode(usageNode);
                     const declScope = ParseTreeUtils.getExecutionScopeNode(decl.node);
                     if (usageScope === declScope) {
-                        if (!isFlowPathBetweenNodes(decl.node, usageNode)) {
+                        // Skip declarations that appear after the usage in the source.
```
Comment (rchiodo) [inline packages/pyright-internal/src/analyzer/typeEvaluator.ts:23307]: @copilot
**[Medium]** The comment claims "such declarations can only be reached via loop back-edges," but this isn't strictly true for all same-scope constructs. An untyped declaration in an `if` branch textually before usage in the `else` branch is flow-unreachable yet would now be included. While the Skeptic confirmed the flow engine at the usage site overrides `effectiveType` for local variables (mitigating the impact on narrowed types), the wider `effectiveType` feeds into metadata flags like `includesVariableDecl` and `addTypeFormForSymbol`. Consider softening the comment to "typically only reached via loop back-edges" and adding a regression test for branching patterns (e.g. `if`/`else` with untyped assignment in only one branch).

File: packages/pyright-internal/src/analyzer/typeEvaluator.ts [hunk 2]
```diff
@@ -23304,7 +23304,15 @@ export function createTypeEvaluator(
...
+                        // Such declarations can only be reached via loop back-edges, and
+                        // including them causes circular evaluation (producing Unknown).
+                        // Declarations that textually precede the usage are retained so
+                        // that order-independent type aliases resolve correctly.
+                        // Note: for the cases filtered out here (decl after usage in same
+                        // scope), the code-flow engine handles loop-carried narrowing when
+                        // it evaluates the type at the actual usage site.
+                        if (decl.node.start >= usageNode.start) {
```
Comment (rchiodo) [inline packages/pyright-internal/src/analyzer/typeEvaluator.ts:23319]: @copilot
**[Medium]** The position heuristic replaces a semantic reachability check, which is the correct fix for the circular-evaluation regressions. However, no test exercises non-loop branching within the same execution scope (e.g. `try`/`except`, `if`/`else`). Add at least one test where an untyped declaration textually precedes usage but is flow-unreachable, to confirm the flow engine's safety net produces the correct narrowed type at the usage site:
```python
def f(flag: bool):
    if flag:
        x = "hello"
        return
    reveal_type(x)  # should be str | Unbound, not str
```

**Review by rchiodo — APPROVED** [review]
Approved via Review Center.

**Review by rchiodo — APPROVED** [review]
Approved via Review Center.
